---
- name: Create Build Directory
  connection: local
  tags: build
  file: path=./roles/cisco-hostname/build/ state=directory
  when:
    - ansible_check_mode

- name: Generate Cisco CLI Configuration from Template
  connection: local
  tags: build
  template:
    src: config-cli.j2 
    dest: ./roles/cisco-hostname/build/{{ inventory_hostname }}-config.txt
  when:
    - ansible_check_mode

- name: Take a Configuration Backup from Device
  connection: local
  tags: bak
  ios_config:
    host: "{{ ansible_ssh_host }}"
    username: "{{ ansible_ssh_user }}"
    password: "{{ ansible_ssh_password }}"
    backup: yes
  ignore_errors: yes
  when:
    - ansible_check_mode

- name: Get current State of the device 
  tags: bak
  connection: local
  ignore_errors: yes
  ios_facts:
      host: "{{ ansible_ssh_host }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_password }}"
  register: iosfacts_out

- name: Copy Facts to File
  connection: local
  ignore_errors: yes
  copy: content="{{ iosfacts_out | to_nice_json }}" dest=./state/{{inventory_hostname}}_iosfacts.json


# Set Hostname on Device from Template
- name: Config Switch Hostname
  tags: oam
  connection: local
  ios_config:
      host: "{{ ansible_ssh_host }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_password }}"
      lines: hostname {{ inventory_hostname }}
  when:
    - not ansible_check_mode



