---
- name: Create Build Directory
  connection: local
  tags: build
  file: path=./roles/cisco-hostname/config/ state=directory
  when:
    - ansible_check_mode

- name: Generate Cisco Configuration from Template
  connection: local
  tags: build
  template:
    src: config.j2 
    dest: ./roles/cisco-hostname/config/{{ inventory_hostname }}.txt
  when:
    - ansible_check_mode
    
# Set Hostname on Device
- name: Config Switch Hostname
  tags: oam
  connection: local
  ios_config:
      host: "{{ ansible_ssh_host }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_password }}"
      lines: hostname {{ inventory_hostname }}
  when:
    - not ansible_check_mode



